vagrant/AT19_DOCKER-COMPOSE/AT19_FRONTEND_CONVERT/WEB-CONVERTER/src/com/jalasoft/Web-converter/blueprints/image_bw_bp.py
#
# @image_bw_bp.py Copyright (c) 2023 Jalasoft.
# 2643 Av Melchor Perez de Olguin, Colquiri Sud, Cochabamba, Bolivia.
# All rights reserved.
#
# This software is the confidential and proprietary information of
# Jalasoft, ("Confidential Information"). You shall not
# disclose such Confidential Information and shall use it only in
# accordance with the terms of the license agreement you entered into
# with Jalasoft.
#

from flask import Blueprint
from flask import render_template
from blueprints.handle_inputs import HandleInputs
from blueprints.converter_base_bp import ConverterBase
from login.user_authenticate import LoggedUser
from dotenv import load_dotenv
import os


image_bw_blueprint = Blueprint('image_bw', __name__)
load_dotenv()
CONVERTER_URL = os.getenv("CONVERTER_URL")
PORT_CONVERTER = os.getenv("PORT_CONVERTER")


class ImageBwController:

    @image_bw_blueprint.route('/image_bw', methods=['GET', "POST"])
    def image_bw():
        """Manages endpoint for image black and white converter"""
        form = HandleInputs()
        user_aut = LoggedUser().is_logged()
        if form.validate_on_submit():
            url = CONVERTER_URL + PORT_CONVERTER + '/imagebw'
            data = {'output_file': form.param1.data}
            return ConverterBase(form, url, data, "image_bw", user_aut['new_ep'], user_aut['link_label'], user_aut['profile_pic']).convert_file()
        return render_template('image_bw.html', form=form, new_ep=user_aut['new_ep'], link_label=user_aut['link_label'], profile_pic=user_aut['profile_pic'])

vagrant/AT19_DOCKER-COMPOSE/AT19_FRONTEND_CONVERT/WEB-CONVERTER/src/com/jalasoft/Web-converter/blueprints/image_flip_bp.py
#
# @image_flip_bp.py Copyright (c) 2023 Jalasoft.
# 2643 Av Melchor Perez de Olguin, Colquiri Sud, Cochabamba, Bolivia.
# All rights reserved.
#
# This software is the confidential and proprietary information of
# Jalasoft, ("Confidential Information"). You shall not
# disclose such Confidential Information and shall use it only in
# accordance with the terms of the license agreement you entered into
# with Jalasoft.
#

from flask import Blueprint
from flask import render_template
from blueprints.handle_inputs import HandleInputs
from blueprints.converter_base_bp import ConverterBase
from login.user_authenticate import LoggedUser
from dotenv import load_dotenv
import os

image_flip_blueprint = Blueprint('image_flip', __name__)
load_dotenv()
CONVERTER_URL = os.getenv("CONVERTER_URL")
PORT_CONVERTER = os.getenv("PORT_CONVERTER")


class ImageFlipController:

    @image_flip_blueprint.route('/image_flip', methods=['GET', "POST"])
    def image_flip():
        """Manages endpoint for image flipper"""
        form = HandleInputs()
        user_aut = LoggedUser().is_logged()        
        if form.validate_on_submit():
            url = CONVERTER_URL + PORT_CONVERTER + '/imageflip'
            data = {'output_file': form.param1.data}
            return ConverterBase(form, url, data, "image_flip", user_aut['new_ep'], user_aut['link_label'], user_aut['profile_pic']).convert_file()
        return render_template('image_flip.html', form=form, new_ep=user_aut['new_ep'], link_label=user_aut['link_label'], profile_pic=user_aut['profile_pic'])

vagrant/AT19_DOCKER-COMPOSE/AT19_FRONTEND_CONVERT/WEB-CONVERTER/src/com/jalasoft/Web-converter/blueprints/image_resize_bp.py
#
# @image_resize_bp.py Copyright (c) 2023 Jalasoft.
# 2643 Av Melchor Perez de Olguin, Colquiri Sud, Cochabamba, Bolivia.
# All rights reserved.
#
# This software is the confidential and proprietary information of
# Jalasoft, ("Confidential Information"). You shall not
# disclose such Confidential Information and shall use it only in
# accordance with the terms of the license agreement you entered into
# with Jalasoft.
#

from flask import Blueprint
from flask import render_template
from blueprints.handle_inputs import HandleInputs
from blueprints.converter_base_bp import ConverterBase
from login.user_authenticate import LoggedUser
from dotenv import load_dotenv
import os

image_resize_blueprint = Blueprint('image_resize', __name__)
load_dotenv()
CONVERTER_URL = os.getenv("CONVERTER_URL")
PORT_CONVERTER = os.getenv("PORT_CONVERTER")


class ImageResizeController:

    @image_resize_blueprint.route('/image_resize', methods=['GET', "POST"])
    def image_resize():
        """Manages endpoint for image resizer"""
        form = HandleInputs()
        user_aut = LoggedUser().is_logged()
        if form.validate_on_submit():
            url = CONVERTER_URL + PORT_CONVERTER + '/imageresize'
            data = {'output_file': form.param1.data, 'new_size': form.param2.data}
            return ConverterBase(form, url, data, "image_resize", user_aut['new_ep'], user_aut['link_label'], user_aut['profile_pic']).convert_file()
        return render_template('image_resize.html', form=form, new_ep=user_aut['new_ep'], link_label=user_aut['link_label'], profile_pic=user_aut['profile_pic'])

vagrant/AT19_DOCKER-COMPOSE/AT19_FRONTEND_CONVERT/WEB-CONVERTER/src/com/jalasoft/Web-converter/blueprints/image_rotate_bp.py
#
# @images_rotate_bp.py Copyright (c) 2023 Jalasoft.
# 2643 Av Melchor Perez de Olguin, Colquiri Sud, Cochabamba, Bolivia.
# All rights reserved.
#
# This software is the confidential and proprietary information of
# Jalasoft, ("Confidential Information"). You shall not
# disclose such Confidential Information and shall use it only in
# accordance with the terms of the license agreement you entered into
# with Jalasoft.
#

from flask import Blueprint
from flask import render_template
from blueprints.handle_inputs import HandleInputs
from blueprints.converter_base_bp import ConverterBase
from login.user_authenticate import LoggedUser
from dotenv import load_dotenv
import os

image_rotate_blueprint = Blueprint('image_rotate', __name__)
load_dotenv()
CONVERTER_URL = os.getenv("CONVERTER_URL")
PORT_CONVERTER = os.getenv("PORT_CONVERTER")


class ImageRotateController:

    @image_rotate_blueprint.route('/image_rotate', methods = ['GET', "POST"])
    def image_rotate():
        """Manages endpoint for image rotator"""
        form = HandleInputs()
        user_aut = LoggedUser().is_logged()
        if form.validate_on_submit():
            url = CONVERTER_URL + PORT_CONVERTER + '/imagerotate'
            data = {'output_file': form.param1.data, 'grades': form.param2.data}
            return ConverterBase(form, url, data, "image_rotate", user_aut['new_ep'], user_aut['link_label'], user_aut['profile_pic']).convert_file()
        return render_template('image_rotate.html', form=form, new_ep=user_aut['new_ep'], link_label=user_aut['link_label'], profile_pic=user_aut['profile_pic'])

vagrant/AT19_DOCKER-COMPOSE/AT19_FRONTEND_CONVERT/WEB-CONVERTER/src/com/jalasoft/Web-converter/templates/about_us.html
{% extends './base.html' %}

{% block title%} Image resize {% endblock %}

{% block body %}

<h1>This is the converter studio</h1>
{% endblock %}

vagrant/AT19_DOCKER-COMPOSE/AT19_FRONTEND_CONVERT/WEB-CONVERTER/src/com/jalasoft/Web-converter/templates/audio_increase_volume.html
{% extends './base.html' %}

{% block title%} Audio volume changer {% endblock %}

{% block body %}

<h1>Audio volume changer</h1>
<link rel="stylesheet" href="{{ url_for('static', filename='css/animations.css') }}">
    <body>
         <form method="post" enctype=multipart/form-data>
            {{ form.hidden_tag() }}
            <div class="input-container">
                <label for="file">File: </label>
                {{ form.file(id="file") }}
                <br></div>
            <div class="input-container">
                <label for="param1">Output type: </label>
                {{ form.param1(id="param1") }}
            <br></div>
            <div class="input-container">
                <label for="param2">Multiplier: </label>
                {{ form.param2(id="param2") }}
            <br></div>

            {{ form.submit(class_="green-button") }}
            {% if download_link %}
                <a href="{{ download_link }}" download class="yellow-button">Download</a>
            {% endif %}
        </form>
    </body>
    <div class="image-container">
        <img src="/static/img/audio_to_audio1.png" height="300px" width="300px" id="image-1">
        <img src="/static/img/audio_to_audio2.png" height="300px" width="300px" id="image-2">
    </div>

        <button id="show-example-button" onclick="alert('Button clicked!')" >Show Example</button>
        <button id="watch-again-button"  onclick="alert('Button clicked!')" >Watch again</button>
        <script src="/static/js/animations.js"></script>

{% endblock %}

vagrant/AT19_DOCKER-COMPOSE/AT19_FRONTEND_CONVERT/WEB-CONVERTER/src/com/jalasoft/Web-converter/templates/audio_to_audio.html
{% extends './base.html' %}

{% block title%} Audio to audio {% endblock %}

{% block body %}
<h1> audio to audio converter </h1>
<link rel="stylesheet" href="{{ url_for('static', filename='css/animations.css') }}">
    <body>
         <form method="post" enctype=multipart/form-data>
            {{ form.hidden_tag() }}
            <div class="input-container">
                <label for="file">File: </label>
                {{ form.file(id="file") }}
                <br></div>
            <div class="input-container">
                <label for="param1">Output type: </label>
                {{ form.param1(id="param1") }}
            <br></div>

            {{ form.submit(class_="green-button") }}
            {% if download_link %}
                <a href="{{ download_link }}" download class="yellow-button">Download</a>
            {% endif %}
        </form>
    </body>
    <div class="image-container">
        <img src="/static/img/audio_to_audio1.png" height="300px" width="300px" id="image-1">
        <img src="/static/img/audio_to_audio2.png" height="300px" width="300px" id="image-2">
    </div>

        <button id="show-example-button" style="display: none;">Show Example</button>
        <button id="watch-again-button">Watch again</button>
        <script src="/static/js/animations.js"></script>


{% endblock %}

vagrant/AT19_DOCKER-COMPOSE/AT19_FRONTEND_CONVERT/WEB-CONVERTER/src/com/jalasoft/Web-converter/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%} {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" id="stylesheet" href="../static/css/base3.css">
    <link rel="shortcut icon" href="../static/img/logo.png" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css2?family=Lilita+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Kanit&display=swap" rel="stylesheet">

</head>

<body>
    <div class="site-content">
        <header class="site-header">
            <div class="container-fluid d-flex justify-content-between">
                <div class="my-title" style="height:100%"> <img src="/static/img/logo.png" alt="Test Image" height="110px" width="124px" style="float:left;" /> <a class="navbar-brand" href="/" style="float:left; padding-left: 10px;">Converter Studio</a> </div>
                <nav class="navbar navbar-expand-lg"> <button class="navbar-toggler d-inline-block" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown"> <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownVideo" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Video converter </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li class="nav-item"> <a class="nav-link" href="{{ url_for('video_to_images.video_to_images') }}">Video to images</a> </li>
                                    <li class="nav-item"> <a class="nav-link" href="{{ url_for('video_to_video.video_to_video') }}">Video to video</a> </li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown"> <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownImage" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Image converter </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li class="nav-item"> <a class="nav-link" href="{{ url_for('image_to_image.image_to_image') }}">Image to image</a> </li>
                                    <li class="nav-item"> <a class="nav-link" href="{{ url_for('image_flip.image_flip') }}">Image flip</a> </li>
                                    <li class="nav-item"> <a class="nav-link" href="{{ url_for('image_bw.image_bw') }}">Image BW</a> </li>
                                    <li class="nav-item"> <a class="nav-link" href="{{ url_for('image_resize.image_resize') }}">Image resize</a> </li>
                                    <li class="nav-item"> <a class="nav-link" href="{{ url_for('image_rotate.image_rotate') }}">Image rotator</a> </li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown"> <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownAudio" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Audio Converter </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li class="nav-item"> <a class="nav-link" href="{{ url_for('audio_to_audio.audio_to_audio') }}">Audio to audio</a> </li>
                                    <li class="nav-item"> <a class="nav-link" href="{{ url_for('audio_increase_volume.audio_increase_volume') }}">Audio vol. changer</a> </li>
                                </ul>
                            </li>

                        </ul>
                        <ul class="navbar-nav">
                             <li class="nav-item dropdown"> <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownStyles" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Styles </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdownStyles">
                                    <li class="nav-item"> <a class="nav-link" id="navStyles1" >AT-19</a> </li>
                                    <li class="nav-item"> <a class="nav-link" id="navStyles2" >Alternative</a> </li>
                                    <li class="nav-item"> <a class="nav-link" id="navStyles3" >Dark minimalist</a> </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </nav>
                <!-- <a class="user-icon" href="/login"> <img src="/static/img/user.png" alt=""> </a> -->
                <div class="nav-item dropdown login_menu">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownLogin" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="{{ profile_pic }}" alt="">
                    </a>
                    <ul class="dropdown-menu container_menu" aria-labelledby="navbarDropdown">
                        <li class="nav-item">
                            <a class="nav-link menu" href="{{ new_ep }}">{{ link_label }}</a>
                        </li>
                    </ul>
                </div>
            </div>
        </header>
    </div>
    <div class="container py-3"> {% block body %} {% endblock %} </div>
    <footer>
      <p>Copyright © 2023 Jalasoft - All rights reserved</p>
    </footer>
    <script src="static/js/styles.js"></script>
    <script src="static/js/animations.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKh"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"> </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"> </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"> </script>
</body>
</html>

vagrant/AT19_DOCKER-COMPOSE/AT19_FRONTEND_CONVERT/WEB-CONVERTER/src/com/jalasoft/Web-converter/templates/image_bw.html
{% extends './base.html' %}

{% block title%} Image BW {% endblock %}

{% block body %}
<h1> Image Black and White converter </h1>
<link rel="stylesheet" href="{{ url_for('static', filename='css/animations.css') }}">
    <body>
         <form method="post" enctype=multipart/form-data>
            {{ form.hidden_tag() }}
            <div class="input-container">
                <label for="file">File: </label>
                {{ form.file(id="file") }}
                <br></div>
            <div class="input-container">
                <label for="param1">Output type: </label>
                {{ form.param1(id="param1") }}
            <br></div>

            {{ form.submit(class_="green-button") }}
            {% if download_link %}
                <a href="{{ download_link }}" download class="yellow-button">Download</a>
            {% endif %}
        </form>
    </body>
    <div class="image-container">
        <img src="/static/img/image_bw.png" id="image-1">
        <img src="/static/img/image.jpg" id="image-2">
    </div>

        <button id="show-example-button" style="display: none;">Show Example</button>
        <button id="watch-again-button">Watch again</button>
        <script src="/static/js/animations.js"></script>


{% endblock %}

vagrant/AT19_DOCKER-COMPOSE/AT19_FRONTEND_CONVERT/WEB-CONVERTER/src/com/jalasoft/Web-converter/templates/image_flip.html
{% extends './base.html' %}

{% block title%} Image flip {% endblock %}

{% block body %}

<h1>Image flipper</h1>
<link rel="stylesheet" href="{{ url_for('static', filename='css/animations.css') }}">
    <body>
        <form method="post" enctype=multipart/form-data>
            {{ form.hidden_tag() }}
            <div class="input-container">
                <label for="file">File: </label>
                {{ form.file(id="file") }}
                <br></div>
            <div class="input-container">
                <label for="param1">Output type: </label>
                {{ form.param1(id="param1") }}
            <br></div>

            {{ form.submit(class_="green-button") }}
            {% if download_link %}
               <a href="{{ download_link }}" download class="yellow-button">Download</a>
            {% endif %}
        </form>
    <div class="image-container">
        <img src="/static/img/image_flip1.jpg" id="image-1">
        <img src="/static/img/image.jpg" id="image-2">
    </div>

        <button id="show-example-button" style="display: none;">Show Example</button>
        <button id="watch-again-button">Watch again</button>
        <script src="/static/js/animations.js"></script>

    </body>


{% endblock %}

vagrant/AT19_DOCKER-COMPOSE/AT19_FRONTEND_CONVERT/WEB-CONVERTER/src/com/jalasoft/Web-converter/templates/image_rotate.html
{% extends './base.html' %}

{% block title%} Image rotate{% endblock %}

{% block body %}

<h1>Image rotator</h1>
<link rel="stylesheet" href="{{ url_for('static', filename='css/animations.css') }}">
    <body>
         <form method="post" enctype=multipart/form-data>
            {{ form.hidden_tag() }}
            <div class="input-container">
                <label for="file">File: </label>
                {{ form.file(id="file") }}
                <br></div>
            <div class="input-container">
                <label for="param1">Output type: </label>
                {{ form.param1(id="param1") }}
            <br></div>
            <div class="input-container">
                <label for="param2">Grades: </label>
                {{ form.param2(id="param2") }}
            <br></div>

            {{ form.submit(class_="green-button") }}
            {% if download_link %}
                <a href="{{ download_link }}" download class="yellow-button">Download</a>
            {% endif %}
        </form>
    </body>
    <div class="image-container">
        <img src="/static/img/image_rotate.jpg" height="300px" width="300px" id="image-1">
        <img src="/static/img/image.jpg" height="300px" width="300px" id="image-2">
    </div>

        <button id="show-example-button" style="display: none;">Show Example</button>
        <button id="watch-again-button">Watch again</button>
        <script src="/static/js/animations.js"></script>

{% endblock %}

vagrant/AT19_DOCKER-COMPOSE/AT19_FRONTEND_CONVERT/WEB-CONVERTER/src/com/jalasoft/Web-converter/templates/image_to_image.html
{% extends './base.html' %}

{% block title%} Image to image {% endblock %}

{% block body %}
<h1> Image to Image converter </h1>
<link rel="stylesheet" href="{{ url_for('static', filename='css/animations.css') }}">
    <body>
         <form method="post" enctype=multipart/form-data>
            {{ form.hidden_tag() }}
            <div class="input-container">
                <label for="file">File: </label>
                {{ form.file(id="file") }}
                <br></div>
            <div class="input-container">
                <label for="param1">Output type: </label>
                {{ form.param1(id="param1") }}
            <br></div>

            {{ form.submit(class_="green-button") }}
            {% if download_link %}
                <a href="{{ download_link }}" download class="yellow-button">Download</a>
            {% endif %}
        </form>
    </body>
    <div class="image-container">
        <img src="/static/img/image_to_image1.png" id="image-1">
        <img src="/static/img/image_to_image2.png" id="image-2">
    </div>

        <button id="show-example-button" style="display: none;">Show Example</button>
        <button id="watch-again-button">Watch again</button>
        <script src="/static/js/animations.js"></script>


{% endblock %}

vagrant/AT19_DOCKER-COMPOSE/AT19_FRONTEND_CONVERT/WEB-CONVERTER/src/com/jalasoft/Web-converter/templates/index.html
{% extends './base.html' %}

{% block title%} Converter Studio {% endblock %}

{% block body %}
<h1>Welcome to Converter Studio!</h1>
<body>

</body>

{% endblock %}

vagrant/AT19_DOCKER-COMPOSE/AT19_FRONTEND_CONVERT/WEB-CONVERTER/src/com/jalasoft/Web-converter/templates/index2.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>CONVERTER</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href="{{url_for('static', filename='css/style.css')}}">
    <script src='main.js'></script>
    <style>
    </style>
</head>
<body>
    <div class="site-content" style="height: auto !important;">
    <header class="site-header">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="/home">
                    <img src="{{ user_image}}" alt="Converter" height="100px" width="120px"/>
                </a>
            </div>
            <div class="name">
                <h3>FLDSMDFR  App</h3>
                <h4>Converter</h4>
            </div>
            <div class="button">
                <a href="http://192.168.100.35:8000/aboutus">About Us</a>
            </div>
            <div class="button2">
                <a href="http://192.168.100.35:8000/signin">Sign in</a>
            </div>
        </div>
    </header>
    </div>
    <ul class="menu-2">
        <li><a href="http://192.168.100.35:8000/videotoimage">Video To Image</a></li>
        <li><a href="http://192.168.100.35:8000/videoconverter">Video Converter</a></li>
        <li><a href="http://192.168.100.35:8000/imageconverter">Image Converter</a></li>
        <li><a href="http://192.168.100.35:8000/audioconverter">Audio Converter</a></li>
        <li><a href="http://192.168.100.35:8000/pdftoimage">PDF to image</a></li>
    </ul>
    <h2> UPLOAD YOUR FILE </h2>
    <form href= "http://192.168.100.35:8000/" enctype='multipart/form-data' method='POST' role="form">
        <input type="file" name="input_file"><br>
        <label1 for="input_file">Extension:</label1>
        <input type="text" name="output_file"><br>
        <label2 for="fps">fps:</label2>
        <input type="text" name="fps"><br>
        <input type="submit" value="Convert"><br>

    </form>
    <div class="Download">
        <a href= "http://localhost:5000/download?file_name=videoplayback.zip" download="videotoimage" title="Download Zip">Download Zip</a>
    </div>
    <div class="Download_Link">
        <p4> Download Link: {{download_link}}
            <a href="http://localhost:5000/download?file_name=videoplayback.zip"></a>
        </p4><br><br>
    </div>
    <h1>Convert your Video to Images</h1>
    <p>By submitting your video to the upload box, our online</p>
    <p>converter helps you convert your video to images.</p>
    <div class="button-step1">
        <a href="#">Step 1</a>
    </div>
    <p1>Select a Converter above</p1>
    <div class="button-step2">
        <a href="#">Step 2</a>
    </div>
    <p2>Submit your file</p2>
    <div class="button-step3">
        <a href="#">Step 3</a>
    </div>
    <p3>Get your Result!</p3>
</body>
</html>

vagrant/AT19_DOCKER-COMPOSE/AT19_FRONTEND_CONVERT/WEB-CONVERTER/src/com/jalasoft/Web-converter/templates/need_be_logged.html
{% extends './base.html' %}

{% block title%} Image BW {% endblock %}

{% block body %}
<h1 style="font-size: 2rem; text-align: center">To access this content you need to be logged in</h1>
<div class="login_icon_container">
    <h2> Please, click <a href="/login">here</a> and login with your google account </h2>
    <a href="/login" class="login_icon" title="login_link"><img src="../static/img/google.png" alt="Google login icon"></a>
</div>
{% endblock %}

vagrant/AT19_DOCKER-COMPOSE/AT19_FRONTEND_CONVERT/WEB-CONVERTER/src/com/jalasoft/Web-converter/templates/pdf.html
{% extends './base.html' %}

{% block title%} Video {% endblock %}

{% block body %}


    <body>
        <form method="post" enctype=multipart/form-data>
            {{ form.hidden_tag() }}
            <label for="file">File:</label>
            {{ form.file(id="file") }}
            <br>
            <label for="output_type">Output type:</label>
            {{ form.output_type(id="output_type") }}
            <br>
            <label for="fps">Fps:</label>
            {{ form.fps(id="fps") }}
            <br>
            {{ form.submit() }}
            <a href="{{ download_link }}" download>Download</a>
        </form>
    </body>


{% endblock %}